baseurl = "https://hbpmedical.github.io/"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-80660232-2"
languageCode = "en-uk"
metadataformat = "yaml"
theme = "hugo-material-docs"
title = "HBP SP8 Repository"

[params]
	# General information
	author = "HBPMedical"
	description = "SP8 subproject (Medical Informatics Platform) for the Human Brain Project."
	copyright = "Released under the MIT license"

	# Repository
	provider = ""
	repo_url = ""

	#version = "1.0.0"
	logo = "images/hbp.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[params.palette]
    	primary = "red"
    	accent  = "teal"

[params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "HBPMedical"
	github  = "HBPMedical"
	email   = "hbp_medicalinformatics@chuv.ch"


#[[menu.main]]
#	name   = "Material"
#	url    = "/"
#	weight = 0

[[menu.main]]
	name   = "HBP SP8"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "documentation/"
	weight = 20

[[menu.main]]
	name   = "Development Process"
	url    = "development-process/"
	weight = 30

[[menu.main]]
	name   = "Software Catalog"
	url    = "software-catalog/"
	weight = 40

[[menu.main]]
	name   = "Technology Stack"
	url    = "technology-stack/"
	weight = 50

[[menu.main]]
	name   = "Technical specifications"
	url    = "https://hbpmedical.github.io/specifications/"
	weight = 60

[[menu.main]]
	name   = "Deployment requirements"
	url    = "https://hbpmedical.github.io/deployment/"
	weight = 60

[[menu.main]]
	name   = "Media"
	url    = "media/"
	weight = 70

[[menu.main]]
	name   = "Search"
	url    = "search/"
	weight = 80

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
