baseurl = "https://hbpmedical.github.io/"
canonifyurls = true
googleAnalytics = "UA-80660232-2"
languageCode = "en-uk"
metadataformat = "yaml"
theme = "hugo-material-docs"
title = "HBP SP8 repository"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.main]]
name = "Release Notes"
url = "/release-notes"
weight = 32
[[menu.main]]
name = "Technology Stack"
url = "software-catalog/stack/"
weight = 31
[[menu.main]]
name = "Software Catalog"
url = "software-catalog/"
weight = 30
[[menu.main]]
name = "UoA"
url = "contributors/uoa"
weight = 29
[[menu.main]]
name = "AUEB"
url = "contributors/aueb"
weight = 28
[[menu.main]]
name = "EPFL"
url = "contributors/epfl"
weight = 27
[[menu.main]]
name = "CHUV"
url = "contributors/chuv"
weight = 26
[[menu.main]]
name = "List of contributors"
url = "contributors/"
weight = 25
[[menu.main]]
name = "Development Process"
url = "development-process/"
weight = 20
[[menu.main]]
name = "Documentation"
url = "documentation/"
weight = 10
[[menu.main]]
name = "HBP SP8"
url = "/"
weight = 0
[params]
author = "HBP SP8 team"
copyright = "Released under the MIT license"
custom_css = []
custom_js = []
description = "SP8 subproject (Medical Informatics Platform) for the Human Brain Project."
favicon = ""
highlight_css = ""
logo = "images/hbp.png"
permalink = "#"
provider = ""
repo_url = "https://github.com/HBPMedical/HBPMedical.github.io"
version = ""
[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"
[params.palette]
accent = "teal"
primary = "red"
[social]
email = "hbp_medicalinformatics@chuv.ch"
github = "HBPMedical"
twitter = "HBPmedical"
