version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout
      - run:
          name: "Checkout content"
          command: git checkout content
      - run:
          name: "Checkout theme"
          command: sh after-git-clone.sh
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
      - run:
          name: "Test Website"
          command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external

workflows:
  version: 2
  build:
    jobs:
      - build