version: 2.1

jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: 'Build static website'
          command: |
            git checkout content
            docker run --rm -P  -v $(pwd):/src jojomi/hugo:0.48

workflows:
  version: 2
  build:
    jobs:
      - build